(webapp): fix tooltip position and reward message
eoscostarica/eosio-dashboard pull request #709
Opened 2021-11-24 01:11 UTC by tetogomez

### Fix tooltip position and reward message

### What does this PR do?

- Resolve #708 
- Resolve #704 
- Resolve #474 

### Steps to test

1. first step
2. next step

#### CheckList

- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-11-24 15:09 UTC, AngeloCG97 approved these changes
LGTM

2021-11-24 15:10 UTC, xavier506 requested changes
please see comments

2021-11-24 15:10 UTC, xavier506 commented on webapp/src/layouts/Dashboard.js
> +// import Collapse from '@material-ui/core/Collapse'
@tetogomez  do we need this comment?

2021-11-24 15:33 UTC, AngeloCG97 commented on webapp/src/components/GeoMap/CountryMap.js
>        <div ref={myRef} style={{ height: '100vh' }} />
We delete inline style

2021-11-25 17:57 UTC, xavier506 approved these changes
LGTM

2021-11-25 18:55 UTC, adriexnet approved these changes

2021-11-25 18:57 UTC, merged