Refactor search components 833
eoscostarica/eosio-dashboard pull request #866
Opened 2022-08-19 15:56 UTC by Torresmorah

### Refactor search component

### What does this PR do?

- Resolve #833 
- Add new component for search based on NodeSearch and ProducerSearch components 
- Use the new component in block  producers, nodes, geo distribution and accounts pages

### Steps to test

1. Run the project locally
2. Test the search bar components in the changed pages

#### CheckList

- [ ] The content is adequate
- [ ] The content is available in both English and Spanish
- [ ] I Ran a spell check

2022-08-20 01:15 UTC, tetogomez requested changes
Please check the comment @Torresmorah 


Also, you touch several components and routes that you can implement the new logic for single responsibility, let me know if U need support for it

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/Accounts/index.js
> +    const accountName = valueAccount?.owner ?? ''
Nullish Coalescing, nice bro!! very nice! 😂

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/Accounts/index.js
> +      const account = await eosApi.getAccount(accountName)
add blank space after const declaration

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/Accounts/index.js
> +      const { code_hash: hash = '' } = await eosApi.getCodeHash(accountName)
same here!

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/Accounts/index.js
>      // eslint-disable-next-line
we can fix this eslint comment wrapping `handleOnSearch` function with useCallback, please take a look!

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/Accounts/index.js
>      // eslint-disable-next-line
same here!

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/BlockProducers/index.js
> +  const chips = CHIPS_NAMES.map((e) => {
we can do that as a single line function

example: 
` const chips = CHIPS_NAMES.map((e) => ({ name: e }))`

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/BlockProducers/index.js
> +    <Grid>
if you won't be using the real potential of the `Grid` or `Box` component is much better just use a simple `div` as a wrapper

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/Nodes/index.js
> +    <Grid>
same here

2022-08-20 01:15 UTC, tetogomez commented on webapp/src/routes/NodesDistribution/index.js
> +    <Grid>
and here!

2022-08-24 13:39 UTC, AngeloCG97 approved these changes
LGTM

2022-08-24 18:37 UTC, fvives99 approved these changes
LGTM

2022-08-25 02:36 UTC, tetogomez approved these changes
LGTM

2022-08-25 02:36 UTC, tetogomez commented on webapp/src/hooks/customHooks/useSearchState.js
> +
delete this blank space

2022-08-25 19:09 UTC, merged