Feature/UI redesign footer #861
eoscostarica/eosio-dashboard pull request #880
Opened 2022-09-02 06:14 UTC by fvives99

### Redesign Footer&Header

### What does this PR do?

- Resolve #861 

### Steps to test

1. make start
2. navigate to http://localhost:3000/ and see footer&header

#### CheckList

- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2022-09-02 06:15 UTC, fvives99 commented
See attached images:

![1](https://user-images.githubusercontent.com/55892352/188070906-350bef7e-ae5b-41b9-b2b9-b464beca1170.png)
![2](https://user-images.githubusercontent.com/55892352/188070913-e5dce4c9-a578-428d-a078-8f2bc28757b6.png)

2022-09-02 20:40 UTC, fvives99 commented
See images for colapsed sidebar

![image](https://user-images.githubusercontent.com/55892352/188232264-cb2ba1fc-196a-4b40-9ff7-a892e350bdaf.png)
![image](https://user-images.githubusercontent.com/55892352/188232279-67b15bfa-8bd9-472d-94b0-4a0e4d74e7f5.png)

2022-09-02 21:34 UTC, Torresmorah approved these changes
LGTM

2022-09-02 22:42 UTC, xavier506 commented on .env.jungle
> +REACT_APP_FEATURE_BUG=[{ "text": "Feature Request/Bug Report", "src": "https://github.com/eoscostarica/eosio-dashboard/issues/new/choose"}]
I think this text reads better like this: 

`"text": "Report a Bug or Request a Feature"`

2022-09-02 22:43 UTC, xavier506 commented on webapp/Dockerfile
> +ARG reac_app_privacy-terms
typo `reac_app..` missing a `t`

2022-09-02 22:44 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +      <Grid container item xs={12} sm={8} justifyContent='flex-start'>
is there an opportunity to refactor from `grid->box` to `divs` here?

2022-09-02 22:47 UTC, xavier506 requested changes
@fvives99  please make sure design styles match @Edwinjrc 's designs

2022-09-03 00:25 UTC, tetogomez requested changes
Please Refactor this PR in order to Remove Box and Grid component

also, there are several commented code

2022-09-07 00:30 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +                This app is Open Source
Why arent we using i18n?

2022-09-07 16:17 UTC, tetogomez approved these changes
LGTM

Just check the code factor comments

2022-09-07 22:38 UTC, tetogomez approved these changes

2022-09-07 22:39 UTC, merged