Feat/update bp info with standard 863
eoscostarica/eosio-dashboard pull request #882
Opened 2022-09-02 15:14 UTC by Torresmorah

### Update the displayed data of nodes and block producers according to bp json standard
 
### What does this PR do?

- Resolves #863
- Resolves #836 
- Resolves #874
- Refactor related components
- Hide "More Info" button on desktop

### Steps to test

1. Run the project locally
2. Check the paths of block producers and nodes

#### CheckList

- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2022-09-02 22:31 UTC, xavier506 approved these changes
LGTM

2022-09-03 00:49 UTC, tetogomez requested changes
just a couple of comments

BTW: good job removing Box components

2022-09-03 00:49 UTC, tetogomez commented on webapp/src/components/NodeCard/index.js
> +  const ShowInfo = ({ cond, title, value }) => {
single return and space after if declaration

```
const ShowInfo = ({ cond, title, value }) => {
    if (!cond && !value)  return <></>
    
    return (
      <>
        <dt className={classes.bold}>{title}</dt>
        <dd>{value}</dd>
      </>
    )
  }

2022-09-03 00:49 UTC, tetogomez commented on webapp/src/components/ProducerCard/index.js
> +    const logo = producerOrg.branding?.logo_256
nice!

2022-09-03 00:49 UTC, tetogomez commented on webapp/src/utils/validate-image.js
> +const isLogoValid = (imgUrl) => {
space after `const or let` declaration and space bofer return

```
const isLogoValid = (imgUrl) => {
  const img = new Image()
  
  img.src = imgUrl
  
  return img.width >= 100 && img.height >= 100
}

2022-09-06 18:59 UTC, merged